### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by appernetic** [fanderzon/lambdasync#15]
Yesterday I had no problem setting up a new project with lambdasync new proj-name and running lambda devserver.

But today I tried to run the lambdasync command and got this:

(node:7188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NoSuchEntity: Role not found for LambdasyncExecRole
serv1:create-seller-account appernetic$ 

Do I need to login to AWS first? And how?

My set-up. 
OSX 10.11
Node v6.7.0
Latest dynamoDB

**Comment by appernetic** [comment]
Tried to do a browser login first to AWS. Then run lambdasync again. Same error.

Installed on Ubuntu Server 14.04 with node 4.3.2. 

Got this error:

molnsys@ubuntu:~$ lambdasync new testproj2
/home/molnsys/.nvm/versions/node/v5.0.0/lib/node_modules/lambdasync/bin/src/index.js:6
const {version} = require('../../package.json');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
molnsys@ubuntu:~$ 

Both with Node 4.3.2 and 5.0 (installed with NVM).

**Comment by appernetic** [comment]
Switched to node 6.2.2 Ubuntu Server and manage to set up a new project.

The went in to the project folder and run  lamdasync and got this error:

lambdasync

# init already run
=====================================
lambdasync init has been run on this project before, did you mean to run just lambdasync to deploy/update your function?

**Comment by appernetic** [comment]
Hadn't installed aws sdk on the server. But after that I could set up a new project and run the devserver but not deploy it:

molnsys@ubuntu:~/versiontest$ lambdasync
(node:4223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NoSuchEntity: Role not found for LambdasyncExecRole

Node v 6.7.0
Ubuntu server 14.0.4
Latest aws sdk

**Comment by fanderzon** [comment]
Thanks for trying out Lambdasync and reporting this issue. There seems to be a problem with Lambdasync automatically creating the AWS role to run your function (and the .aws credential/config files).

I will try to replicate it myself and hopefully have a fix out today.

**Comment by appernetic** [comment]
Ok, great! I had use of the scaffolding and devserver at least.
